#!/usr/sbin/nft -f

flush ruleset

table inet filter {
	chain input {
		type filter hook input priority filter;

		tcp dport 80 accept \
		comment "Allow HTTP"

		tcp dport 443 accept \
		comment "Allow HTTPS"
	}
	chain forward {
		type filter hook forward priority filter;
	}
	chain output {
		type filter hook output priority filter;
	}
}
